In [146]:
import pandas as pd

In [147]:
data = pd.read_csv('data.csv')
data.head()

,customer_id,tenure_months,monthly_charges,contract_type,support_calls,payment_method,favorite_color,churn
0,CUST00001,7,510.66,One year,2,Credit card,Purple,No
1,CUST00002,56,405.77,Monthly,3,Bank transfer,Green,No
2,CUST00003,48,1061.10,Monthly,0,Bank transfer,Yellow,Yes
3,CUST00004,32,1307.16,Monthly,2,Debit card,Red,Yes
4,CUST00005,32,640.58,Monthly,0,UPI,Black,Yes

In [148]:
data.columns

Index(['customer_id', 'tenure_months', 'monthly_charges', 'contract_type',
       'support_calls', 'payment_method', 'favorite_color', 'churn'],
      dtype='object')

In [149]:
data = data.drop(['customer_id','favorite_color'],axis=1)

In [150]:
data

,tenure_months,monthly_charges,contract_type,support_calls,payment_method,churn
0,7,510.66,One year,2,Credit card,No
1,56,405.77,Monthly,3,Bank transfer,No
2,48,1061.10,Monthly,0,Bank transfer,Yes
3,32,1307.16,Monthly,2,Debit card,Yes
4,32,640.58,Monthly,0,UPI,Yes
...,...,...,...,...,...,...
7995,33,823.33,One year,3,UPI,No
7996,52,727.71,Monthly,1,Credit card,No
7997,25,882.18,Monthly,1,Cash,No
7998,10,672.46,One year,1,Bank transfer,No
7999,13,337.09,Monthly,1,Cash,No

In [151]:
data['contract_type'].value_counts()
data['support_calls'].value_counts()
data['payment_method'].value_counts()

payment_method
UPI              2786
Debit card       1620
Credit card      1446
Bank transfer    1336
Cash              812
Name: count, dtype: int64

In [152]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)

ohe_encoded = ohe.fit_transform(data[['payment_method','contract_type']])

ohe_encoded_data = pd.DataFrame(
    ohe_encoded,
    columns=ohe.get_feature_names_out(),
    index=data.index
)

ohe_encoded_data

,payment_method_Bank transfer,payment_method_Cash,payment_method_Credit card,payment_method_Debit card,payment_method_UPI,contract_type_Monthly,contract_type_One year,contract_type_Two year
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
7995,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
7996,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
7997,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
7998,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7999,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [153]:
import pickle

with open('ohe.pkl','wb') as file:
    pickle.dump(ohe,file)

In [154]:

data= pd.concat([data.drop(['contract_type','payment_method'],axis=1),ohe_encoded_data],axis=1)
data

,tenure_months,monthly_charges,support_calls,churn,payment_method_Bank transfer,payment_method_Cash,payment_method_Credit card,payment_method_Debit card,payment_method_UPI,contract_type_Monthly,contract_type_One year,contract_type_Two year
0,7,510.66,2,No,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,56,405.77,3,No,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,48,1061.10,0,Yes,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,32,1307.16,2,Yes,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,32,640.58,0,Yes,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7995,33,823.33,3,No,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
7996,52,727.71,1,No,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
7997,25,882.18,1,No,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
7998,10,672.46,1,No,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7999,13,337.09,1,No,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [155]:
data.head(10)

,tenure_months,monthly_charges,support_calls,churn,payment_method_Bank transfer,payment_method_Cash,payment_method_Credit card,payment_method_Debit card,payment_method_UPI,contract_type_Monthly,contract_type_One year,contract_type_Two year
0,7,510.66,2,No,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,56,405.77,3,No,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,48,1061.10,0,Yes,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,32,1307.16,2,Yes,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,32,640.58,0,Yes,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
5,62,446.30,6,No,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
6,7,235.51,3,Yes,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
7,51,693.85,5,Yes,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
8,15,677.24,1,Yes,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
9,7,600.20,5,Yes,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [156]:
X = data.drop('churn',axis=1)
y = data['churn']
X.columns = X.columns.astype(str)

In [157]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

y_train = y_train.map({'Yes': 1, 'No': 0}).astype('float32')
y_test = y_test.map({'Yes': 1, 'No': 0}).astype('float32')

In [158]:
X.columns

Index(['tenure_months', 'monthly_charges', 'support_calls',
       'payment_method_Bank transfer', 'payment_method_Cash',
       'payment_method_Credit card', 'payment_method_Debit card',
       'payment_method_UPI', 'contract_type_Monthly', 'contract_type_One year',
       'contract_type_Two year'],
      dtype='object')

In [159]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [160]:
import pickle

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [161]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\valla\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (6.33.6)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (1.78.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\valla\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\valla\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\valla\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\valla\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\valla\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.5.20)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\valla\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\valla\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\valla\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\valla\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\valla\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\valla\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\valla\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [162]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import TensorBoard,CSVLogger,EarlyStopping
from datetime import datetime

In [163]:
log_dir = 'log/fits'+ datetime.now().strftime("%Y%m%d-%H%M%S")

tb_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

csv_callback = CSVLogger("traning_log.csv")

earlystopping = EarlyStopping(
    monitor='val_accuracy',
    patience=2,
    mode='max',
    restore_best_weights=True
)

In [164]:
%pip install tensorboard

Requirement already satisfied: tensorboard in c:\users\valla\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (1.78.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (3.8)
Requirement already satisfied: numpy>=1.12.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (2.3.5)
Requirement already satisfied: packaging in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (25.0)
Requirement already satisfied: pillow in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (11.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (6.33.6)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (80.9.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\valla\anaconda3\lib\site-packages (from tensorboard) (3.1.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\valla\anaconda3\lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\valla\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [165]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

model.compile(
    optimizer = "adam",
    loss = "binary_crossentropy",
    metrics = ['accuracy']
)

model.fit(
    X_train,
    y_train,
    epochs = 70,
    validation_split = 0.2,
    callbacks = (tb_callback,csv_callback,earlystopping)
)

c:\Users\valla\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/70
160/160 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7170 - loss: 0.5434 - val_accuracy: 0.7688 - val_loss: 0.4904
Epoch 2/70
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7486 - loss: 0.5092 - val_accuracy: 0.7703 - val_loss: 0.4895
Epoch 3/70
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7516 - loss: 0.5062 - val_accuracy: 0.7633 - val_loss: 0.4883
Epoch 4/70
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7520 - loss: 0.5051 - val_accuracy: 0.7625 - val_loss: 0.4854

In [170]:
model.save("ann.keras")

In [167]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_33 (Dense)                │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,645 (33.77 KB)

 Trainable params: 2,881 (11.25 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,764 (22.52 KB)

In [168]:
y_pred = model.predict(X_test)

# Convert probabilities into class labels
y_pred = (y_pred >= 0.5).astype(int).ravel()

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy: 0.76
              precision    recall  f1-score   support

         0.0       0.81      0.86      0.84      1149
         1.0       0.59      0.50      0.54       451

    accuracy                           0.76      1600
   macro avg       0.70      0.68      0.69      1600
weighted avg       0.75      0.76      0.75      1600

In [169]:
import sys
import os
import subprocess

tb_path = os.path.join(
    os.path.dirname(sys.executable),
    "Scripts",
    "tensorboard.exe"
)

process = subprocess.Popen([
    tb_path,
    "--logdir", os.path.abspath("logs/fit"),
    "--port", "6006"
])

print("TensorBoard started. PID:", process.pid)

TensorBoard started. PID: 20972